version: 2
jobs:
   build:
     docker:
       - image: circleci/golang:latest
     steps:
       - checkout
       - run: git clone --no-checkout --depth 1 git@github.com:develar/7zip-bin.git
       - run: ls -la
       - run: 7zip-bin/tree/master/linux/x64/7za e gccgo-7.1.0-003.7z
       - run: echo "hello world"
