version: 2
jobs:
   build:
     docker:
       - image: circleci/golang:latest
     steps:
       - checkout
       - run: mkdir -p ~/.ssh
       - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
       - run: ssh git@github.com git-lfs-authenticate develar/7zip-bin.git download
       - run: git lfs pull
       - run: ls -la
       - run: chmod +x ./7zip-bin/linux/x64/7za
       - run: ./7zip-bin/linux/x64/7za e gccgo-7.1.0-003.7z
       - run: echo "hello world"
