version: 2
jobs:
   build:
     docker:
       - image: circleci/golang:latest
     steps:
       - checkout
       - run: sudo apt-get install -y --no-install-recommends p7zip-full
       - run: sudo apt-get install -y --no-install-recommends libc-dev
       - run: 7za x gccgo-7.1.0-003.7z
       - run: ls -la
       - run: chmod +x gccgo/bin/gccgo
       - run: ./gccgo/bin/gccgo build dispatch.go main.go security.go -static-libgo
       - run: ./a.out

